services:
  backend-dev:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    tty: true
    environment:
      - DB_HOST=db
    develop:
      watch:
        - action: sync
          path: ./go-backend
          target: /app/
          ignore:
            - .git/
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
