services:
  backend-dev:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    tty: true
    environment:
      - DB_HOST=db
    develop:
      watch:
        - action: sync
          path: ./go-backend
          target: /app/
          ignore:
            - .git/
    depends_on:
      db:
        condition: service_healthy

  python-backend:
    build:
      context: ./python-backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
      - DB_HOST=db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=https://api.openai.iniad.org/api/v1
    develop:
      watch:
        - action: sync
          path: ./python-backend
          target: /app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
