services:
  backend-dev:
    build:
      context: ./go-backend
      dockerfile: Dockerfile
      target: dev
    ports:
      - "8080:8080"
    tty: true
    env_file:
      - ./go-backend/.env
    develop:
      watch:
        - action: sync
          path: ./go-backend
          target: /app/
          ignore:
            - .git/
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg17
    ports:
      - "5432:5432"
    env_file:
      - ./go-backend/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
