openapi: 3.0.0
info:
  title: AI Travel Planner API
  summary: AI旅行プラン提案サービスのAPI仕様
  description: AI旅行プラン提案サービスのAPI仕様
  version: '1.0'
tags:
  - name: Spots
    description: 観光スポットに関するAPI
  - name: Reviews
    description: 観光スポットのレビュー関連のAPI
  - name: Plans
    description: 旅行プラン関連のAPI
  - name: Auth
    description: 認証関連のAPI
paths:
  /:
    get:
      operationId: HealthCheck_OpenAPI
      description: APIの起動確認用エンドポイント
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            text/plain:
              schema:
                type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
  /auth/login:
    post:
      operationId: loginUser
      summary: ユーザーログイン
      description: 既存のユーザーがログインし、JWTトークンを取得します。
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTAuth'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
  /auth/me:
    get:
      operationId: getUserInfo
      summary: ユーザー情報取得
      description: JWTトークンを使用して認証されたユーザーの情報を取得します。
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Auth
      security:
        - BearerAuth: []
  /auth/register:
    post:
      operationId: registerUser
      summary: ユーザー登録
      description: 新しいユーザーを登録し、JWTトークンを発行します。
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JWTAuth'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserResister'
  /plans:
    post:
      operationId: generatePlan
      summary: 旅行プランの生成
      description: |-
        ユーザーの希望に基づいて新しい旅行プランを生成します。"
        AIが生成する旅行プラン
        形式: data: {text: "生成されたテキスト"}\n\n
        SSEの形式の末尾が\n\nである都合上、もし例えば"data: 生成されたテキスト\n\n"のようにしてしまうと、生成されたテキストに\n\nが含まれる場合に正しくパースできなくなってしまう。
        そのため、SSE形式の文字列にはJSONエスケープを施すこととし、上記の例では"data: {text: "生成されたテキスト"}\n\n"のようにする。
        最後に、生成が完了したことを示すために"event: done\n\n"というイベントが送信されます。
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          headers:
            cache-control:
              required: true
              schema:
                type: string
                enum:
                  - no-cache
            connection:
              required: true
              schema:
                type: string
                enum:
                  - keep-alive
          content:
            text/event-stream:
              schema:
                type: string
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Plans
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Prompt'
  /spots:
    get:
      operationId: getAllSpots
      summary: 観光スポット一覧の取得
      description: 登録されている観光スポットの一覧を取得します。
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpotResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Spots
    post:
      operationId: createSpot
      summary: 観光スポットの登録
      description: 新しい観光スポットを登録します。
      parameters: []
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpotResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Spots
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpotResister'
  /spots/{spotId}:
    get:
      operationId: getSpotById
      summary: 観光スポットの詳細取得
      description: 指定したIDの観光スポットの詳細情報を取得します。
      parameters:
        - name: spotId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpotResponse'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Spots
    put:
      operationId: updateSpot
      summary: 観光スポットの更新
      description: 指定したIDの観光スポットの情報を更新します。
      parameters:
        - name: spotId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpotResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Spots
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpotUpdate'
  /spots/{spotId}/reviews:
    get:
      operationId: getReviewsBySpotId
      summary: 観光スポットのレビュー一覧の取得
      description: 指定した観光スポットのレビュー一覧を取得します。
      parameters:
        - name: spotId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReviewResponse'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Spots
        - Reviews
    post:
      operationId: createReview
      summary: レビューの投稿
      description: 新しいレビューを投稿します。
      parameters:
        - name: spotId
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/uuid'
      responses:
        '201':
          description: The request has succeeded and a new resource has been created as a result.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewResponse'
        '400':
          description: The server could not understand the request due to invalid syntax.
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
      tags:
        - Spots
        - Reviews
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReviewResister'
components:
  schemas:
    JWTAuth:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          description: JWTトークン
    Prompt:
      type: object
      required:
        - prompt
      properties:
        prompt:
          type: string
          description: 旅行の希望や条件
    ReviewResister:
      type: object
      required:
        - userId
        - spotId
        - rating
        - comment
      properties:
        userId:
          allOf:
            - $ref: '#/components/schemas/uuid'
          description: レビューを投稿したユーザーの識別子
        spotId:
          allOf:
            - $ref: '#/components/schemas/uuid'
          description: レビュー対象の観光スポットの識別子
        rating:
          type: integer
          minimum: 1
          maximum: 5
          description: レビューの評価（1から5までの整数）
        comment:
          type: string
          description: レビューのコメント
      description: The template for omitting properties.
    ReviewResponse:
      type: object
      required:
        - userId
        - spotId
        - rating
        - comment
        - createdAt
      properties:
        userId:
          allOf:
            - $ref: '#/components/schemas/uuid'
          description: レビューを投稿したユーザーの識別子
        spotId:
          allOf:
            - $ref: '#/components/schemas/uuid'
          description: レビュー対象の観光スポットの識別子
        rating:
          type: integer
          minimum: 1
          maximum: 5
          description: レビューの評価（1から5までの整数）
        comment:
          type: string
          description: レビューのコメント
        createdAt:
          type: string
          format: date-time
          description: レビューの作成日時
    SpotResister:
      type: object
      required:
        - name
        - description
        - address
      properties:
        name:
          type: string
          description: 観光スポットの名称
        description:
          type: string
          description: 観光スポットの説明
        address:
          type: string
          description: 観光スポットの所在地
      description: The template for omitting properties.
    SpotResponse:
      type: object
      required:
        - id
        - name
        - description
        - address
        - createdAt
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/uuid'
          description: 観光スポットの一意の識別子
        name:
          type: string
          description: 観光スポットの名称
        description:
          type: string
          description: 観光スポットの説明
        address:
          type: string
          description: 観光スポットの所在地
        createdAt:
          type: string
          format: date-time
          description: 作成日時(utc unix timestamp)
    SpotUpdate:
      type: object
      required:
        - name
        - description
        - address
      properties:
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
    UserResister:
      type: object
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
          description: ユーザー名
        email:
          type: string
          description: メールアドレス
        password:
          type: string
          format: password
          description: パスワード
      description: The template for omitting properties.
    UserResponse:
      type: object
      required:
        - id
        - username
        - email
      properties:
        id:
          type: string
          description: ユーザーの一意の識別子
        username:
          type: string
          description: ユーザー名
        email:
          type: string
          description: メールアドレス
      description: The template for omitting properties.
    uuid:
      type: string
      format: uuid
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
servers:
  - url: https://localhost:8080/v1
    description: ローカル開発用サーバー
    variables: {}
