# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: oapi
generate:
  strict-server: true
  std-http-server: true
  models: true
  embedded-spec: true
  # client: true
additional-imports:
  - package: github.com/google/uuid
    alias: uuid


output: ./oapi/server.gen.go
