// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Review struct {
	ID        uuid.UUID          `json:"id"`
	SpotID    uuid.UUID          `json:"spot_id"`
	UserID    uuid.UUID          `json:"user_id"`
	Rating    int32              `json:"rating"`
	Comment   string             `json:"comment"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Spot struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	Address         string             `json:"address"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EmbeddingOpenai *pgvector.Vector   `json:"embedding_openai"`
}
