// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: Spot.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const createSpot = `-- name: CreateSpot :one
INSERT INTO Spot (
    Id,
    Name,
    Description,
    Address
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, description, address, created_at, embedding
`

type CreateSpotParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Address     string    `json:"address"`
}

func (q *Queries) CreateSpot(ctx context.Context, arg CreateSpotParams) (Spot, error) {
	row := q.db.QueryRow(ctx, createSpot,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Address,
	)
	var i Spot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.CreatedAt,
		&i.Embedding,
	)
	return i, err
}

const deleteSpot = `-- name: DeleteSpot :exec
DELETE FROM Spot
WHERE Id = $1
`

func (q *Queries) DeleteSpot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpot, id)
	return err
}

const getSpot = `-- name: GetSpot :one
SELECT id, name, description, address, created_at, embedding FROM Spot
WHERE Id = $1
`

func (q *Queries) GetSpot(ctx context.Context, id uuid.UUID) (Spot, error) {
	row := q.db.QueryRow(ctx, getSpot, id)
	var i Spot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.CreatedAt,
		&i.Embedding,
	)
	return i, err
}

const listSpots = `-- name: ListSpots :many
SELECT id, name, description, address, created_at, embedding FROM Spot
ORDER BY Created_at DESC
`

func (q *Queries) ListSpots(ctx context.Context) ([]Spot, error) {
	rows, err := q.db.Query(ctx, listSpots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spot
	for rows.Next() {
		var i Spot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.CreatedAt,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSpotsByVector = `-- name: SearchSpotsByVector :many
SELECT id, name, description, address, created_at, embedding FROM Spot
WHERE embedding IS NOT NULL
ORDER BY embedding <-> $1
LIMIT 10
`

func (q *Queries) SearchSpotsByVector(ctx context.Context, embedding *pgvector.Vector) ([]Spot, error) {
	rows, err := q.db.Query(ctx, searchSpotsByVector, embedding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spot
	for rows.Next() {
		var i Spot
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Address,
			&i.CreatedAt,
			&i.Embedding,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpot = `-- name: UpdateSpot :one
UPDATE Spot
SET 
    Name = $2,
    Description = $3,
    Address = $4
WHERE Id = $1
RETURNING id, name, description, address, created_at, embedding
`

type UpdateSpotParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Address     string    `json:"address"`
}

func (q *Queries) UpdateSpot(ctx context.Context, arg UpdateSpotParams) (Spot, error) {
	row := q.db.QueryRow(ctx, updateSpot,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Address,
	)
	var i Spot
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Address,
		&i.CreatedAt,
		&i.Embedding,
	)
	return i, err
}

const updateSpotEmbedding = `-- name: UpdateSpotEmbedding :exec
UPDATE Spot
SET embedding = $2
WHERE Id = $1
`

type UpdateSpotEmbeddingParams struct {
	ID        uuid.UUID        `json:"id"`
	Embedding *pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateSpotEmbedding(ctx context.Context, arg UpdateSpotEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateSpotEmbedding, arg.ID, arg.Embedding)
	return err
}
