name: Go Ci
# もしmainブランチのgo-backendディレクトリ内のファイル、またはこのワークフローファイル自体が変更された場合にトリガーされます。
on:
  push:
    branches: [ main ]
    paths:
      - "go-backend/**"
      - ".github/workflows/go_ci.yaml"
  pull_request:
    branches: [ main ]
    paths:
      - "go-backend/**"
      - ".github/workflows/go_ci.yaml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-backend
    services:
      db:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: app_user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_db
        # サービスが準備完了したことを確認するためのヘルスチェック
        options: >-
          --health-cmd pg_isready
          --health-interval 4s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache-dependency-path: |
            go-backend/go.sum

      - name: Install dependencies
        run: |
          go mod download

      - name: Run tests
        run: |
          go test -tags="integration" ./... -v
        env:
          DB_HOST: 127.0.0.1
